# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1058f8085b832e7c80ac44fa861270d91ee20dbe631417b7902531fec22aa4c39230c002da1a1b02c6aa6fc3ccd55ab1a2aa1644bbf7db5a1f544cd49c20ab83

test:
  secret_key_base: c9cf61f80e5dbc562a8b5ada7ba3027cf110fc275245d6796a4be07aa2ce6429094cbf00b59dc5d80e870438120da02c837ddf986fa73d52d74577f3efd0bbd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
